default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: surf_development

test:
  <<: *default
  database: surf_test

production:
  <<: *default
  database: surf_production
  username: api
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
