default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: surf_development

test:
  <<: *default
  database: surf_test

production:
  <<: *default
  database: surf_staging
  username: surf
  password: password
  host:     surf-staging-db.cxpztbbgreq6.us-west-2.rds.amazonaws.com
  port:     5432
